river: Import custom init
This is a squash of the following commits:

  lake: Kang m8's init to set variant properties

    * Based loosely on m8's as of c15efa1ffa8e67469dedc14c779030d3405c0821.

    * Use SKU as opposed to MID as motorola uses these.

    * REVVLRY+ is a lake rebrand for T-Mobile, so we need to set T-Mobile
      IMS properties.

    * Let GMS Client ID be set in makefile in common tree.

    * Let all SKU's other than "XT1965-T" fall through to lake's unlocked
       model.

  Change-Id: I8bb694340ab02f0bcfb95a09337e14c8fd9017b6

  lake: Correctly define libinit location

    * Adresses: error: 'system/core/init/Android.bp:95:1: "libinit" depends on undefined module "libinit_msm8953"'

    Change-Id: Ib663a0dea66abc4c4266989345d057a6237f99fd

Change-Id: I8bb694340ab02f0bcfb95a09337e14c8fd9017b6
lake: Convert libinit to extention of common libinit

Change-Id: I6113ac927d312ebffaba1ce3aecb09bc89671024

lake: Rename libinit override function to avoid duplicate symbol

Change-Id: I29ffe3ea9560681ba6ca2d219131dbd658b28332